#!/bin/bash

# Resting-state fMRI - Wrapper Script



## Pre-processing


### DICOM to NIFTI conversion

bash rsfmri_dicom2nifti.sh

### Brain extraction

bash rsfmri_brain_extraction.sh

### Melodic design file generation (generic and subject-specific)

bash rsfmri_design_generator.sh

### Conversion of fieldmaps to radians and running single-subject melodic

bash rsfmri_melodic+fmap_rads.sh



## ICA manual component classification

####### At this stage ICA components generated by melodic need to be manually classified for all or a subset (if using a automatic component classification tool)
####### before script can proceed

echo "If ICA components need to be manually classified as signal or noise in FSLeyes for all or a subset of subjects then this script needs to be exited. Please read the following messages..."
sleep 1
echo "______"
sleep 1
echo "The script 'rsfmri_manual_comp_classification.sh' should be loaded to produce the FSLeyes layout required for component classification."
sleep 1
echo "______"
sleep 1
echo "If you now complete manual component classification then make sure to remove pre-processing subscripts before executing this script."
sleep 1
echo "______"
sleep 1
echo "The script will now pause for 10 seconds to allow the user to exit."
sleep 10



## Automated component classification (via pyFIX) and removal of noise components

bash rsfmri_ICA_noise_removal.sh



## Group ICA and Dual Regression

bash rsfmri_groupica+dualr.sh



## Data generation

bash rsfmri_func_con_stats.sh